name: Vuepress Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn install

      - name: Vuepress Build
        run: yarn build

      - name: Push Changes
        run: |
          git config --global user.name 'Bot Brian'
          git add --force -- docs/
          git commit -m "Built Website Assets"
          git push origin master
